server:
  port: 8899
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        bootstrap: true
        git:
          clone-on-start: true
          force-pull: true
          default-label: manage-profiles
          uri: https://gitlab.com/vichet.chann/smf-config.git
          username: vichet.chann@allweb.com.kh
          password: RXPzUTcUgZ4ZPSsvVTGG
          repos:
            smf-config: https://gitlab.com/vichet.chann/smf-config/config-repo
            pattern: smf-config*/dev*
               
